github: [llybin]
custom: ['https://www.paypal.me/llybin', 'https://money.yandex.ru/to/41001252061112', 'BTC: bc1q2efcwfs7f9pzncj5qv7xxrmntvempup6tr9vgg', 'ETH: 0xAC8bA41C8BeB07398512A893e1f72E6B95D06694', 'LTC: ltc1qqashju57hag8rppwu6u424ctyewp0ck6k7qyut']
