language: minimal

services:
  - docker

env:
  - COMPOSE_FILE=docker-compose.yml

script:
  - cp .env.default .env
  - docker-compose build
  - docker-compose up -d db
  - docker-compose run service pybabel compile -d locale
  - docker-compose run service coverage run ./manage.py test
  - docker-compose run service coverage report
