language: minimal

services:
  - docker

env:
  - COMPOSE_FILE=docker-compose.yml

script:
  - cp .env.default .env
  - docker-compose build
  - docker-compose up -d db
  - docker-compose run service pybabel compile -d locale
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker-compose run service coverage run ./manage.py test
  - docker-compose run service coverage report
  - docker-compose run $ci_env service codecov
  - docker-compose run $ci_env service python-codacy-coverage -r /code/coverage.xml
