version: '3'
services:
  db:
    image: postgres:10.11
    hostname: db
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.8
    hostname: redis
    volumes:
      - redis_data:/data

  service:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      APP_MIGRATE: "on"
      APP_COMPILE_LOCALE: "on"
      START_APP: "on"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.celery", "worker", "-l", "info", "-c", "2"]
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      APP_COMPILE_LOCALE: "on"
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.celery", "beat", "-l", "info"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgresql_data:
  redis_data:
