version: '3'
services:
  db:
    image: postgres:10.11-alpine
    hostname: db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7-alpine
    hostname: redis
    volumes:
      - redis_data:/data

  service:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: ["./wait-for-it.sh", "db:5432", "--", "./docker-entrypoint.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.celery", "worker", "-l", "info"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.celery", "beat", "-l", "info"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgresql_data:
  redis_data:
